@extends("frontend.layout")
@section("content")
    <div class="problems-content content">
        <div class="problems-detail rules ">
            <div class="bordered">
                <a href="{{ url()->previous() }}" class="back">
                    <i>
                        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.292892 7.29289C-0.0976315 7.68342 -0.0976315 8.31658 0.292892 8.70711L6.65685 15.0711C7.04738 15.4616 7.68054 15.4616 8.07107 15.0711C8.46159 14.6805 8.46159 14.0474 8.07107 13.6569L2.41421 8L8.07107 2.34315C8.46159 1.95262 8.46159 1.31946 8.07107 0.928932C7.68054 0.538408 7.04738 0.538408 6.65685 0.928932L0.292892 7.29289ZM16 7L0.999999 7V9L16 9V7Z" fill="black"/>
                        </svg>
                    </i>
                    <div class="info">
                        <strong>{{ __("box.public_offer") }}</strong>
                    </div>
                </a>
            </div>
            <div class="pa-15">
                <ul class="rules">

                    @if(app()->getLocale() == "ru")
                    <li>Соглашение о пользовании информационной системой sogboling.uz</li>
                    <li>1. Термины и определения</li>
                    <li>1.1. Оператор – штаб по реагированию сигналов при администрации хокимията г.Ташкент, осуществляющий свою деятельность в соответствии с законодательством Республики Узбекистан, нормативными правовыми актами города Ташкент.</li>
                    <li>1.2. Пароль - уникальная последовательность буквенно-цифровых символов, вводимая пользователем при регистрации в сервисе, информационной системе города Ташкент в целях обеспечения последующего доступа Пользователя к данной информационной системе, сервису.</li>
                    <li>1.3. Пользователь – физическое лицо, желающее получить или получившее в установленном порядке доступ к информационной системе sogboling.uz </li>
                    <li>1.4. Регистрация – первичный ввод информации для доступа к сервису, информационной системе, информационному ресурсу города Ташкент.</li>
                    <li>1.5. Сервис - программное приложение, программное и (или) техническое средство, обеспечивающее взаимодействие внутри или между информационными системами, информационными ресурсами города Ташкент.</li>

                    <li>2. Общие положения</li>
                    <li>2.1. Настоящим Соглашением определяются права и обязанности Оператора и Пользователя при организации доступа Пользователя к Сервису, а также при использовании Пользователем функциональных возможностей сервисов и информационных систем города Ташкент. Соглашение вступает в силу с момента выражения Пользователем согласия с его условиями в порядке, предусмотренном пунктом 2.3 Соглашения.</li>
                    <li>2.2. Начиная использовать информационную систему города Ташкент и (или) сервис /отдельные функции в информационной системе города Ташкент и (или) сервисе, либо пройдя процедуру регистрации, Пользователь считается принявшим условия Соглашения в полном объеме.</li>
                    <li>2.3. Соглашение может быть изменено Оператором без специального уведомления, новая редакция Соглашения вступает в силу с момента ее размещения в информационно-телекоммуникационной сети «Интернет» по указанному в настоящем пункте адресу, если иное не предусмотрено новой редакцией Соглашения. Любые изменения, дополнения, а также новые редакции Соглашения равно распространяются на всех пользователей, присоединившихся к Соглашению, в том числе присоединившихся к Соглашению ранее даты изменений, дополнений или новых редакций. В случае если Пользователь продолжает использовать функциональные возможности информационной системы и (или) сервиса после публикации изменений Соглашения, Пользователь тем самым признается принявшим соответствующие изменения. Действующая редакция Соглашения находится на странице по адресу: https://sogboling.uz</li>
                    <li>2.4. В случае несогласия Пользователя с какими-либо из требований к сервису, информационной системе города Ташкент, установленных законодательством Республики Узбекистан, правовыми актами города Ташкент, актами Оператора, настоящим Соглашением, Пользователь не в праве пользоваться информационной системой.</li>
                    <li>2.5. В случае использования материалов сайта в сети Интернет или бумажных носителях – ссылка на первоисточник обязательна.</li>

                    <li>3. Регистрация Пользователя, использование сервисов, информационных систем и ресурсов города Ташкент</li>
                    <li>3.1. Регистрация Пользователя в Сервисе осуществляется после предоставления Пользователем определенного набора сведений на web-странице Сервиса, и создания учетной записи Пользователя в соответствии с требованиями Сервиса.</li>
                    <li>3.2. На любом этапе пользования Сервиса Пользователь обязуется предоставлять достоверную и полную информацию. Пользователь обязуется поддерживать предоставляемую им информацию в актуальном состоянии. Если Пользователь предоставляет неверную информацию или у Оператора есть основания полагать, что предоставленная Пользователем информация неполна или недостоверна, Оператор имеет право по своему усмотрению заблокировать либо удалить учетную запись Пользователя и (или) отказать Пользователю в использовании Сервиса (либо их отдельных функций).</li>
                    <li>3.3. Использование Сервиса означает согласие Пользователя на обработку любой информации, в том числе необходимой для корректной работы и/или сбора статистики использования сервисов системы (в том числе cookie) или предоставляемой Пользователем самостоятельно, включая персональные данные, а также согласие на получение информации о предоставлении ему государственных услуг, о деятельности органов государственной власти города Ташкент и подведомственных им организаций, иных организаций. Указанная информация может быть предоставлена с применением не голосовых коммуникаций (путем рассылки уведомлений внутренними инструментами Сервиса или же по сети подвижной радиотелефонной связи коротких текстовых sms-сообщений, рассылки ussd-сообщений и др.), посредством направления сведений по информационно-телекоммуникационной сети «Интернет» на предоставленный Пользователем номер телефона и (или) адрес электронной почты.</li>
                    <li>3.4. Пользователь самостоятельно несет ответственность за безопасность (устойчивость к угадыванию) используемого им пароля, а также самостоятельно обеспечивает конфиденциальность своего пароля и других средств идентификации. Пользователь самостоятельно несет ответственность за все действия (а также их последствия), совершенные под учетной записью Пользователя в рамках или с использованием Сервиса, включая случаи добровольной передачи Пользователем данных для доступа к учетной записи Пользователя третьим лицам на любых условиях (в том числе по договорам или соглашениям). При этом все действия в рамках или с использованием Сервиса, совершенные под учетной записью Пользователя, считаются произведенными самим Пользователем, за исключением случаев, когда Пользователь заранее уведомил Оператора о несанкционированном доступе к Сервису с использованием учетной записи Пользователя и/или о любом нарушении (подозрениях о нарушении) конфиденциальности своего пароля, других средств идентификации.</li>
                    <li>3.5. Пользователь обязан немедленно уведомить Оператора о любом случае несанкционированного (не разрешенного Пользователем) доступа к Сервису с использованием учетной записи Пользователя и/или о любом нарушении (подозрениях о нарушении) конфиденциальности своего пароля, иных средств идентификации. В целях безопасности Пользователь обязан самостоятельно осуществлять безопасное завершение работы под своей учетной записью по окончании каждой сессии работы с соблюдением требований к Сервису. Оператор не отвечает за возможную потерю или порчу данных, а также другие последствия любого характера, которые могут произойти из-за нарушения Пользователем положений этой части Соглашения.</li>
                    <li>3.6. Оператор вправе в случаях, определенных настоящим Соглашениям, устанавливать ограничения в использовании Сервиса и их частей для учетных записей всех Пользователей, либо для отдельных категорий Пользователей.</li>

                    <li>4. Права и обязанности Сторон</li>
                    <li>4.1. Пользователь обязан:</li>
                    <li>4.1.1. Обеспечить своими силами и за свой счет доступ в информационно-телекоммуникационную сеть «Интернет», а также настройку и защиту от несанкционированного использования своего оборудования, а также оперативно реагировать при обнаружении случаев такого использования.</li>
                    <li>4.1.2. Обеспечивать сохранность пароля Пользователя и других средств идентификации Пользователя.</li>
                    <li>4.1.3. Принять полную ответственность за все обращения и действия, предпринятые через принадлежащую ему учетную запись, имевшие место после регистрации Пользователя.</li>
                    <li>4.1.4. Соблюдать условия настоящего Соглашения.</li>
                    <li>4.2. Пользователь имеет право:</li>
                    <li>4.2.1. Использовать функциональные возможности Сервиса в соответствии с требованиями к соответствующим сервисам и информационным системам, а также в соответствии с настоящим Соглашением.</li>
                    <li>4.2.2. В установленном порядке направлять обращения Оператору, содержащие вопросы относительно технического функционирования Сервиса.</li>
                    <li>4.3. При использовании Сервиса Пользователь не вправе:</li>
                    <li>4.3.1. Загружать, посылать, передавать или любым другим способом размещать и/или распространять контент, который является незаконным, вредоносным, клеветническим, оскорбляет нравственность, демонстрирует (или является пропагандой) насилия и жестокости, нарушает права интеллектуальной собственности, пропагандирует ненависть и/или дискриминацию людей по расовому, этническому, половому, религиозному, социальному признакам, содержит оскорбления в адрес каких-либо лиц или организаций, содержит элементы (или является пропагандой) порнографии, детской эротики, представляет собой рекламу (или является пропагандой) услуг сексуального характера (в том числе под видом иных услуг), разъясняет порядок изготовления, применения или иного использования наркотических веществ или их аналогов, взрывчатых веществ или иного оружия.</li>
                    <li>4.3.2. Нарушать права третьих лиц, в том числе несовершеннолетних лиц и/или причинять им вреда в любой форме.</li>
                    <li>4.3.3. Выдавать себя за другого человека или представителя организации и/или сообщества без достаточных на то прав, в том числе за сотрудников Оператора, а также применять любые другие формы и способы незаконного представительства других лиц, а также вводить пользователей или Оператора в заблуждение относительно свойств и характеристик каких-либо субъектов или объектов.</li>
                    <li>4.3.4. Загружать, посылать, передавать или любым другим способом размещать и/или распространять контент, при отсутствии прав на такие действия согласно законодательству Республики Узбекистан, нормативным правовым актам города Ташкент, актам Оператора или каким-либо договорным отношениям.</li>
                    <li>4.3.5. Загружать, посылать, передавать или любым другим способом размещать и/или распространять не разрешенную специальным образом рекламную информацию и спам.</li>
                    <li>4.3.6. Загружать, посылать, передавать или любым другим способом размещать и/или распространять какие-либо материалы, содержащие вредоносные программы или другие компьютерные коды, файлы или программы, предназначенные для нарушения, уничтожения либо ограничения функциональности любого компьютерного или телекоммуникационного оборудования или программ, для осуществления несанкционированного доступа, а также серийные номера к коммерческим программным продуктам и программы для их генерации, логины, пароли и прочие средства для получения несанкционированного доступа к платным ресурсам в информационно-телекоммуникационной сети «Интернет», а также размещения ссылок на вышеуказанную информацию.</li>
                    <li>4.3.7. Несанкционированно собирать и хранить персональные данные других лиц.</li>
                    <li>4.3.8. Нарушать нормальную работу Сервиса;</li>
                    <li>4.3.9. Содействовать действиям, направленным на нарушение ограничений и запретов, налагаемых Соглашением.</li>
                    <li>4.3.10. Другим образом нарушать нормы законодательства.</li>
                    <li>4.4. Оператор обязан:</li>
                    <li>4.4.1. Обеспечить функционирование Сервиса относящихся к ведению Оператора, а также исполнять другие полномочия, установленные законодательством Республики Узбекистан, правовыми актами города Ташкент, актами Оператора.</li>
                    <li>4.4.2. Предоставить Пользователю доступ к Сервису при соблюдении настоящего Соглашения.</li>
                    <li>4.4.3. В установленном порядке обеспечить безопасность, сохранность и неразглашение сведений, предоставляемых Пользователем.</li>
                    <li>4.4.4. Осуществлять иные обязательства, предусмотренные настоящим Соглашением.</li>
                    <li>4.5. Оператор имеет право:</li>
                    <li>4.5.1. Отказать Пользователю в регистрации и использовании возможностей сервисов, информационных систем города Ташкент, в доступе к Сервису, в случаях, предусмотренных законодательством Республики Узбекистан, нормативным правовыми актами города Ташкент, настоящим Соглашением.</li>
                    <li>4.5.2. Без предупреждения приостановить использование Сервиса Пользователем в случаях:
                        <ul>
                            <li>•	нарушения Пользователем условий данного Соглашения или осуществления Пользователем действий, которые Оператор обоснованно считает нарушающими условия Соглашения;</li>
                            <li>•	в связи с непредвиденными проблемами технического характера или обстоятельствами, связанными с безопасностью;</li>
                            <li>•	вследствие создания помех и любых нарушений со стороны Пользователя в отношении сервисов, информационных систем и ресурсов города Ташкент, включая использование любых устройств, программного обеспечения.</li>
                        </ul>
                    </li>
                    <li>4.5.3. Направлять Пользователю сообщения, содержащие организационно-техническую информацию о функционировании Сервиса, а также о деятельности Оператора и иных органов исполнительной власти города Ташкент, организаций.</li>
                    <li>4.5.4. Привлекать к обеспечению функционирования сервисов и информационных систем города Ташкент, ведению информационных ресурсов города Ташкент третьих лиц в установленном порядке.</li>
                    <li>4.5.5. Производить профилактические работы в сервисах и информационных системах города Ташкент с временным приостановлением их работы.</li>
                    <li>4.6. Оператор не несет ответственности за:</li>
                    <li>4.6.1. Аварии, сбои или перебои в функционировании Сервиса, в доступе к Сервису, связанные с нарушениями в работе оборудования, систем связи или сетей, которые обеспечиваются, подаются, эксплуатируются и/или обслуживаются третьими лицами.</li>
                    <li>4.6.2. Ущерб, понесенный Пользователем в результате:
                        <ul>
                            <li>•	наличия "вирусов" и иных вредоносных программ в оборудовании и программном обеспечении, используемом Пользователем для доступа к Сервису</li>
                            <li>•	нарушения Пользователем настоящего Соглашения;</li>
                            <li>•	неправомерных действий третьих лиц, в том числе связанных с использованием учетной записи Пользователя, а также с использованием сведений о пользователе, предоставленных им в ходе использования Сервиса, если такие сведения стали доступны третьим лицами не по вине Оператора.</li>
                        </ul>
                    </li>
                    <li>4.7. Пользователь и Оператор не несут ответственности за неисполнение или ненадлежащее исполнение настоящего Соглашения, если надлежащее исполнение оказалось невозможным вследствие наступления обстоятельств непреодолимой силы.</li>
                    <li>5. Прочие условия</li>
                    <li>5.1. Настоящее Соглашение регулируется и толкуется в соответствии с законодательством Республики Узбекистан. Вопросы, не урегулированные настоящим Соглашением, подлежат разрешению в соответствии с законодательством Республики Узбекистан. Все возможные споры, вытекающие из отношений, регулируемых настоящим Соглашением, разрешаются в порядке, установленном действующим законодательством Республики Узбекистан.</li>
                    <li>5.2. Условия данного Соглашения действуют до тех пор, пока одна из сторон не заявит о своем намерении выйти из Соглашения, если законодательством Республики Узбекистан и нормативными правовыми актами города Ташкент не установлено иное.</li>

                    @elseif(app()->getLocale() == "uz")
                        <li>Sogbling.uz axborot tizimidan foydalanish to'g'risida kelishuv</li>
                        <li>1. Termin va ta'riflar</li>
                        <li>1.1. Operator - o'z faoliyatini O'zbekiston Respublikasi qonunchiligiga, Toshkent shahrining normativ-huquqiy hujjatlariga muvofiq amalga oshiruvchi, Toshkent shahar hokimligi ma'muriyati huzuridagi signallarga javob berish shtabi.</li>
                        <li>1.2. Foydalanuvchi - sogboling.uz axborot tizimidan belgilangan tartibda foydalanishni istagan yoki foydalanish huquqiga ega bo'lgan jismoniy shaxs.</li>
                        <li>1.3. Parol - foydalanuvchi keyinchalik ushbu xizmatga kirishni ta'minlash uchun xizmatga ro'yhatdan o'tish paytida foydalanuchi tomonidan kiritilgan alifbo-raqamli belgilarning noyob ketma-ketligi.</li>
                        <li>1.4. Ro'yxatdan o'tish - bu xizmatga, axborot tizimiga, Toshkent shahrining axborot resursiga kirish uchun ma'lumotlarning dastlabki kiritilishi.</li>
                        <li>1.5. Xizmat - bu Toshkent shahri axborot tizimlari, axborot manbalari yoki ular o'rtasida o'zaro aloqani ta'minlovchi dasturiy ta'minot, (yoki) texnik vositalar.</li>

                        <li>2. Umumiy qoidalar</li>
                        <li>2.1. Ushbu Shartnoma foydalanuvchining Xizmatga kirishni tashkil etishda, shuningdek Foydalanuvchi Toshkent shahri xizmatlari va axborot tizimlarining funksional imkoniyatlaridan foydalanishda Operator va Foydalanuvchi huquqlari va majburiyatlarini belgilarydi. Shartnoma 2.3-bandda belgilangan tartibda Foydalanuvchi o'z shartlariga rozilik bildirgan paytdan boshlab kuchga kiradi.</li>
                        <li>2.2. Toshkent shahrining axborot tizimidan va (yoki) servis / individual funksiyalardan foydalanishni Toshkent shahri va (yoki) servisning axborot tizimidan foydalanishni boshlaganda yoki ro'yxatdan o'tish jarayoni tugagandan so'ng, foydalanuvchi Shartnoma shartlarini to'liq qabul qildi deb hisoblanadi.</li>
                        <li>2.3. Shartnoma Operator tomonidan maxsus ogohlantirishsiz o'zgartirilishi mumkin, shartnomaning yangi talqini ushbu bandda ko'rsatilgan manzil bo'yicha "Internet" axborot-telekommunikasiya tarmog'iga joylashtirilgan paytdan boshlab kuchga kiradi, agar shartnomaning yangi tahririda boshqacha qoida nazarda tutilmagan bo'lsa. Shartnomadagi har qanday o'zgartirishlar, qo'shimchalar, shuningdek yangi tahrirlar Shartnomaga qo'shilgan barcha foydalanuvchilarga, shu jumladan o'zgartirishlar, qo'shimchalar yoki yangi nashrlarni kiritish sanasidan oldinroq qo'shilganlarga ham qo'llaniladi. Аgar Foydalanuvchi axborot tizimining va (yoki) xizmatlarning funksional imkoniyatlaridan Shartnomaga o'zgartirishlar e'lon qilinganidan keyin foydalanishni davom ettirsa, foydalanuvchi tegishli o'zgartirishlarni qabul qilgan deb xisoblanadi. Shartnomaning joriy versiyasi https://sogboling.uz saytida joylashgan</li>
                        <li>2.4. Аgar Foydalanuvchi xizmatga qo'yiladigan talablarning har biriga rozi bo'lmasa, O'zbekiston Respublikasining qonun hujjatlari, Toshkent shahrining huquqiy hujjatlari, Operator hujjatlari, ushbu Shartnoma bilan belgilangan Toshkent shahrining axborot tizimi, foydalanuvchi ushbu axborot tizimidan foydalanishga haqli emas.</li>
                        <li>2.5. Saytdagi materiallardan Internetda yoki bosma nusxada foydalanganda manba ko'rsatilishi shart.</li>

                        <li>3. Toshkent shahrida foydalanuvchilarni ro'yxatdan o'tkazish, xizmatlardan, axborot tizimlari va resurslaridan foydalanish</li>
                        <li>3.1. Foydalanuvchini Xizmatda ro'yxatdan o'tkazish Foydalanuvchi Xizmatning veb-sahifasida ma'lum bir ma'lumot to'plamini taqdim etgandan va Xizmatning talablariga muvofiq Foydalanuvchi akkauntni yaratgandan so'ng amalga oshiriladi./li>
                        <li>3.2. Xizmatdan foydalanishning har qanday bosqichida Foydalanuvchi aniq va to'liq ma'lumotlarni taqdim etishga majburdir. Foydalanuvchi o'zi taqdim etgan ma'lumotlarni yangilab turish majburiyatini oladi. Аgar Foydalanuvchi noto'g'ri ma'lumot taqdim etsa yoki Operator Foydalanuvchi tomonidan taqdim etilgan ma'lumot to'liq emas yoki noto'g'ri ekanligiga ishonch hosil qilsa, Operator o'z xohishiga ko'ra foydalanuvchi akkauntini blokirovka qilishga yoki uni o'chirishga va (yoki) foydalanuvchidan Xizmatdan (yoki ularning individual funksiyalaridan) voz kechishga haqlidir.</li>
                        <li>3.3. Xizmatdan foydalanish, foydalanuvchining har qanday ma'lumotni, shu jumladan to'g'ri ishlashi va / yoki tizim xizmatlaridan (shu jumladan cookie-fayllardan) foydalanishi yoki foydalanuvchi tomonidan mustaqil ravishda taqdim etilgan statistik ma'lumotlarni to'plashi uchun zarur bo'lgan ma'lumotlarni qayta ishlashga roziligini anglatadi, shuningdek shaxsiy ma'lumotlar, shuningdek, davlat tomonidan taqdim etilgan ma'lumotlar to'g'risida ma'lumot olishga rozilik bildiradi shuningdek, unga davlat xizmatlari ko'rsatish to'g'risida, Toshkent shahri davlat hokimiyati va uning bo'ysunuvchi tashkilotlar, boshqa tashkilotlar faoliyati to'g'risida ma'lumot olishga rozilik berish. Ko'rsatilgan ma'lumotlar "Internet" axborot va telekommunikasiya tarmog'i orqali ma'lumot yuborish orqali ovozsiz aloqadan foydalangan holda (Xizmatning ichki vositalari orqali xabarlarni yuborish yoki qisqa matnli SMS xabarlarni mobil radiotelefon tarmog'i orqali yuborish, ussd-so'rov yuborish va hk) Foydalanuvchi tomonidan taqdim etilgan telefon raqamiga va (yoki) elektron pochta manziliga.</li>
                        <li>3.4. Foydalanuvchi o'zi foydalanadigan parolning xavfsizligi (taxmin qilishning qarshiligi) uchun javobgardir va shuningdek, parol va boshqa identifikasiya qilish vositalarining maxfiyligini ta'minlaydi. Foydalanuvchi Foydalanuvchi tomonidan xizmat ichida yoki undan foydalanishda sodir bo'lgan barcha harakatlar (shuningdek ularning oqibatlari) uchun, shu jumladan foydalanuvchi tomonidan foydalanuvchi akkauntiga kirish uchun ma'lumotni istalgan shartlar bilan uchinchi shaxslarga ixtiyoriy ravishda berish hollari uchun (shu jumladan shartnomalar yoki bitmlar bo'yicha). Shu bilan birga, Foydalanuvchi akkauntida amalga oshirilgan Xizmat ichidagi yoki undan foydalanuvchi tomonidan qilingan barcha harakatlar, foydalanuvchi tomonidan amalga oshirilgan deb hisoblanadi, Foydalanuvchi hisobidan foydalangan holda Xizmatga ruxsatsiz kirish to'g'risida va / yoki uning parolining maxfiyligi buzilganligi va boshqa identifikatsiya qilish usullari to'g'risida Operatorga xabar beradi.</li>
                        <li>3.5. Foydalanuvchi akkauntidan foydalangan holda xizmatga ruxsatsiz kirish (foydalanuvchi tomonidan tasdiqlanmagan) va / yoki uning parolining maxfiyligi yoki boshqa identifikasiya qilish vositalarining buzilishi (buzilish shubhasi) to'g'risida har qanday holatlar to'g'risida Operatorga darhol xabar qilishi shart. Xavfsizlik maqsadida, foydalanuvchi har bir ish sessiyasining oxirida Xizmatga qo'yiladigan talablarga muvofiq ravishda o'z akkaunti bo'yicha ishlarni xavfsiz ravishda o'chirib qo'yishi shart. Operator ma'lumotlarni yo'qolishi yoki shikastlanishi, shuningdek Foydalanuvchi tomonidan ushbu Shartnomaning qoidalarini buzishi natijasida yuzaga kelishi mumkin bo'lgan har qanday boshqa tabiatning oqibatlari uchun javobgar bo'lmaydi.</li>
                        <li>3.6. Operator ushbu Shartnomalarda belgilangan hollarda, barcha foydalanuvchilarning yoki ba'zi foydalanuvchilarning akkauntlari uchun Xizmatdan va uning qismlaridan foydalanishga cheklovlar o'rnatish huquqiga ega.</li>

                        <li>4. Tomonlarning huquq va majburiyatlari</li>
                        <li>4.1. Foydalanuvchi quyidagilarga majbur:</li>
                        <li>4.1.1. O'z kuchi va o'z hisobidan "Internet" axborot-tyelekommunikasiya tarmog'iga kirishni ta'minlashi, shuningdek ularning uskunalarini ruxsatsiz ishlatilishini sozlashi va himoya qilishi, va bunday foydalanish holatlari aniqlanganda tezkor choralarni ko'rishi.</li>
                        <li>4.1.2. Foydalanuvchi parolining va boshqa identifikasiya qilish vositalarining saqlanishini ta'minlashi kerak.</li>
                        <li>4.1.3. Foydalanuvchi ro'yxatdan o'tganidan keyin sodir bo'lgan barcha hisob-kitoblar orqali amalga oshirilgan barcha so'rovlar va harakatlar uchun to'liq javobgarlikni o'z zimmasiga oladi./li>
                        <li>4.1.4. Ushbu Shartnoma shartlariga rioya qilish.</li>
                        <li>4.2. Foydalanuvchi quyidagi huquqlarga ega:</li>
                        <li>4.2.1. Xizmatning funksional imkoniyatlaridan tegishli xizmatlar va axborot tizimlariga qo'yiladigan talablarga va ushbu Shartnomaga muvofiq foydalanish huquqiga ega.</li>
                        <li>4.2.2. Belgilangan tartibda Operatorga Xizmatning texnik ishlashiga oid savollarni yuborish.</li>
                        <li>4.3. Xizmatdan foydalanganda, foydalanuvchi quyidagi huquqlarga ega emas:</li>
                        <li>4.3.1. Noqonuniy, zararli, tuhmat, axloqni buzuvchi, zo'ravonlik va shafqatsizlikni namoyish qiluvchi (yoki tashviqot qiladigan), intellektual mulk huquqlarini buzadigan, odamlarga nisbatan nafratni va / yoki kamsitishni targ'ib qiluvchi tarkibiy qismlarni yuklash, yuborish, boshqa yo'llar bilan yuborish yoki tarqatish, irqiy, etnik, jinsiy, diniy, ijtimoiy xususiyatlar, har qanday shaxs yoki tashkilotga nisbatan haqoratlarni o'z ichiga olgan, pornografiya elementlarini (yoki targ'ibotni) o'z ichiga olgan, bolalar erotikligi, jinsiy xizmatlarni reklama qilish (yoki targ'ib qilish), giyohvandlik vositalarini yoki ularning o'xshashlarini, portlovchi moddalarni yoki boshqa qurollarni tayyorlash, ishlatish yoki boshqa foydalanish tartibini tushuntiradi.</li>
                        <li>4.3.2. Uchinchi shaxslarning, shu jumladan voyaga yetmaganlarning huquqlarini buzish va / yoki ularga har qanday shaklda zarar yetkazish.</li>
                        <li>4.3.3. Boshqa shaxsni yoki tashkilotning va / yoki jamoaning vakilini, shu jumladan Operator xodimlarini, huquqlarini o'zlashtirmaslik, shuningdek boshqalarning noqonuniy vakillik qilishning boshqa shakllari va usullaridan foydalanish, shuningdek foydalanuvchilar yoki Operatorning xususiyatlari nisbatan chalg'itish har qanday mavzu yoki obyekt.</li>
                        <li>4.3.4. O'zbekiston Respublikasi qonunlariga, Toshkent shahrining normativ-huquqiy hujjatlariga, Operator aktlariga yoki har qanday shartnoma munosabatlariga muvofiq bunday harakatlarga huquqlari bo'lmagan taqdirda, tarkibni yuklash, yuborish, yoki boshqa usul bilan tarqatish.</li>
                        <li>4.3.5. Maxsus ruxsat etilmagan reklama va spamlarni yuklash, yuborish yoki boshqa usul bilan tarqatish.</li>
                        <li>4.3.6. Zararli dasturlarni yoki boshqa kompyuter kodlarini, fayllarni yoki dasturlarni har qanday kompyuter yoki telekommunikasiya uskunalari yoki dasturlarining ishini buzish, cheklash, ruxsatsiz ishlash uchun mo'ljallangan materiallarni yuklash, yuborish, boshqa yo'l bilan yuborish va / yoki tarqatish. tijorat dasturiy mahsulotlariga va ularni yaratish uchun dasturlarga seriyali raqamlarni, loginlarni, parollarni va "Internet" axborot-telekommunikasiya tarmog'ida pulli manbalardan ruxsatsiz kirishni olish uchun boshqa vositalarni, shuningdek yuqorida ko'rsatilgan ma'lumotlarga havolalarni joylashtirish.</li>
                        <li>4.3.7. Boshqalarning shaxsiy ma'lumotlarini ruxsatsiz to'plash va saqlash.</li>
                        <li>4.3.8. Xizmatning normal ishlashini buzish;</li>
                        <li>4.3.9. Shartnoma tomonidan o'rnatilgan cheklovlar va taqiqlarni buzishga qaratilgan harakatlarga yordam berish.</li>
                        <li>4.3.10. Boshqa tarzda qonunni buzish.</li>
                        <li>4.4. Operator quyidagi majburiyatlarni bajaradi:</li>
                        <li>4.4.1. Operatorning vakolatiga taalluqli Xizmatning ishlashini ta'minlash, shuningdek O'zbekiston Respublikasining qonunlarida, Toshkent shahrining normativ-huquqiy hujjatlarida, Operator hujjatlari bilan belgilangan boshqa vakolatlarni amalga oshirish.</li>
                        <li>4.4.2. Foydalanuvchi bilan ushbu Shartnoma asosida Xizmatga kirish huquqini berish.</li>
                        <li>4.4.3. Belgilangan tartibda foydalanuvchi tomonidan taqdim etilgan ma'lumotlarning saqlanishini, xavfsizligini va oshkor qilinmasligini ta'minlash.</li>
                        <li>4.4.4. Ushbu Shartnomada nazarda tutilgan boshqa majburiyatlarni bajarish.</li>
                        <li>4.5. Operator quyidagi huquqlarga ega:</li>
                        <li>4.5.1. O'zbekiston Respublikasining qonunlarida, Toshkent shahrining normativ-huquqiy hujjatlarida, ushbu Shartnomada ko'zda tutilgan hollarda, Foydalanuvchini ro'yxatdan o'tish va xizmatning imkoniyatlaridan foydalanishni rad etish</li>
                        <li>4.5.2. Foydalanuvchi tomonidan quyidagi hollarda ogohlantirishsiz Xizmatdan foydalanishni to'xtatib qo'yish:
                            <ul>
                                <li>•	Foydalanuvchi tomonidan ushbu Shartnoma shartlari buzilishi yoki Foydalanuvchi tomonidan Operator ushbu Shartnoma shartlarini buzgan deb hisoblagan xatti-harakatlarni amalga oshirsa;</li>
                                <li>•	kutilmagan texnik yoki xavfsizlik muammolari tufayli;</li>
                                <li>•	foydalanuvchining Toshkent shahri xizmatlari, axborot tizimlari va resurslariga, shu jumladan har qanday qurilmalar, dasturiy ta'minotlardan foydalanishiga to'sqinlik qilishi va har qanday huquqbuzarliklar tufayli.</li>
                            </ul>
                        </li>
                        <li>4.5.3. Foydalanuvchiga Xizmatning ishlashi, shuningdek Operator va Toshkent shahridagi boshqa ijro organlari, tashkilotlar faoliyati to'g'risida tashkiliy va texnik ma'lumotlarni o'z ichiga olgan xabarlarni yuborish.</li>
                        <li>4.5.4. Toshkent shahri xizmatlari va axborot tizimlari ishini ta'minlashga, Toshkent shahrining axborot resurslarini belgilangan tartibda saqlashga uchinchi shaxslarni jalb qilish.</li>
                        <li>4.5.5. Ularning faoliyati vaqtincha to'xtatib qo'yilgan holda Toshkent shahar xizmatlari va axborot tizimlarida profilaktika ishlarini olib borish.</li>
                        <li>4.6. Operator quyidagi uchun javobgar emas:</li>
                        <li>4.6.1. Uchinchi shaxslar tomonidan yetkazib beriladigan, yetkazib beriladigan, ishlaydigan va / yoki xizmat ko'rsatadigan asbob-uskunalar, aloqa tizimlari yoki tarmoqlarining nosozliklari bilan bog'liq bo'lgan, xizmatga kirishda xizmatdagi avariyalar, uzilishlar yoki uzilishlar.</li>
                        <li>4.6.2. Foydalanuvchi tomonidan yetkazilgan zarar:
                            <ul>
                                <li>•	Foydalanuvchi tomonidan xizmatga kirish uchun foydalanadigan asbob-uskunalar va dasturlarda "viruslar" va boshqa zararli dasturlarning mavjudligi;</li>
                                <li>•	Foydalanuvchi ushbu Shartnomani buzsa;</li>
                                <li>•	uchinchi shaxslarning noqonuniy xatti-harakatlari, shu jumladan Foydalanuvchi akkauntidan foydalanish bilan bog'liq, shuningdek, xizmatdan foydalanish paytida u taqdim etgan foydalanuvchi to'g'risidagi ma'lumotlardan, agar bunday ma'lumotlar Operatorning aybisiz uchinchi shaxslarga yetkazilgan bo'lsa.</li>
                            </ul>
                        </li>
                        <li>4.7. Foydalanuvchi va Operator ushbu Shartnomani bajarmaganligi yoki lozim darajada bajarmaganligi uchun javobgar emas, agar yengib bo'lmas kuch ta'sirida yuzaga kelganligi sababli uni bajarish imkoni bo'lmasa.</li>
                        <li>5. Boshqa shartlar</li>
                        <li>5.1. Ushbu Bitim O'zbekiston Respublikasining qonunlariga muvofiq tartibga solinadi va sharhlanadi. Ushbu Bitim bilan tartibga solinmagan masalalar O'zbekiston Respublikasi qonunlariga muvofiq hal qilinishi kerak. Ushbu Shartnoma bilan tartibga solinadigan munosabatlardan kelib chiqadigan barcha mumkin bo'lgan tortishuvlar O'zbekiston Respublikasining amaldagi qonunchiligida belgilangan tartibda hal qilinadi.</li>
                        <li>5.2. Ushbu Shartnomaning shartlari, agar O'zbekiston Respublikasi qonunlarida va Toshkent shahrining normativ-huquqiy hujjatlarida boshqacha qoida nazarda tutilgan bo'lmasa, tomonlardan biri ushbu Bitimdan chiqish niyati to'g'risida bildirgan paytgacha amal qiladi.</li>

                    @elseif(app()->getLocale() == "cyrillic_uz")

                        <li>Sogbling.uz ахборот тизимидан фойдаланиш тўғрисида келишув</li>
                        <li>1. Термин ва таърифлар</li>
                        <li>1.1. Оператор - ўз фаолиятини Ўзбекистон Республикаси қонунчилигига, Тошкент шаҳрининг норматив-ҳуқуқий ҳужжатларига мувофиқ амалга оширувчи, Тошкент шаҳар ҳокимлиги маъмурияти ҳузуридаги сигналларга жавоб бериш штаби.</li>
                        <li>1.2. Фойдаланувчи - sogboling.uz ахборот тизимидан белгиланган тартибда фойдаланишни истаган ёки фойдаланиш ҳуқуқига эга бўлган жисмоний шахс.</li>
                        <li>1.3. Парол - фойдаланувчи кейинчалик ушбу хизматга киришини таъминлаш учун хизматга рўйхатдан ўтиш пайтида фойдаланувчи томонидан киритилган алифбо-рақамли белгиларнинг ноёб кетма-кетлиги.1.4. Рўйхатдан ўтиш - бу хизматга, ахборот тизимига, Тошкент шаҳрининг ахборот ресурсига кириш учун асосий маълумот.</li>
                        <li>1.4. Рўйхатдан ўтиш - бу хизматга, ахборот тизимига, Тошкент шаҳрининг ахборот ресурсига кириш учун маълумотларнинг дастлабки киритилиши.</li>
                        <li>1.5. Хизмат - бу Тошкент шаҳри ахборот тизимлари, ахборот манбалари ёки улар ўртасида ўзаро алоқани таъминловчи дастурий таъминот,  (ёки) техник воситалар.</li>

                        <li>2. Умумий қоидалар</li>
                        <li>2.1. Ушбу Шартнома фойдаланувчининг Хизматга киришини ташкил этишда, шунингдек Фойдаланувчи Тошкент шаҳри хизматлари ва ахборот тизимларининг функционал имкониятларидан фойдаланишда Оператор ва Фойдаланувчи ҳуқуқлари ва мажбуриятларини белгилайди. Шартнома 2.3-бандда белгиланган тартибда Фойдаланувчи ўз шартларига розилик билдирган пайтдан бошлаб кучга киради.</li>
                        <li>2.2. Тошкент шаҳрининг ахборот тизимидан ва (ёки) сервис / индивидуал функциялардан фойдаланишни Тошкент шаҳри ва (ёки) сервиснинг ахборот тизимидан фойдаланишни бошлаганда ёки рўйхатдан ўтиш жараёни тугагандан сўнг, фойдаланувчи Шартнома шартларини тўлиқ қабул қилди деб ҳисобланади.</li>
                        <li>2.3. Шартнома Оператор томонидан махсус огоҳлантиришсиз ўзгартирилиши мумкин, шартноманинг янги талқини ушбу бандда кўрсатилган манзил бўйича "Интернет" ахборот-телекоммуникация тармоғига жойлаштирилган пайтдан бошлаб кучга киради, агар шартноманинг янги таҳририда бошқача қоида назарда тутилмаган бўлса. Шартномадаги ҳар қандай ўзгартиришлар, қўшимчалар, шунингдек янги таҳрирлар Шартномага қўшилган барча фойдаланувчиларга, шу жумладан ўзгартиришлар, қўшимчалар ёки янги нашрларни киритиш санасидан олдинроқ қўшилганларга ҳам қўлланилади. Агар Фойдаланувчи ахборот тизимининг ва (ёки) хизматларнинг функционал имкониятларидан Шартномага ўзгартиришлар эълон қилинганидан кейин фойдаланишни давом эттирса, фойдаланувчи тегишли ўзгартиришларни қабул қилган деб хисобланади. Шартноманинг жорий версияси https://sogboling.uz сайтида жойлашган</li>
                        <li>2.4. Агар Фойдаланувчи хизматга қўйиладиган талабларнинг ҳар бирига рози бўлмаса, Ўзбекистон Республикасининг қонун ҳужжатлари, Тошкент шаҳрининг ҳуқуқий ҳужжатлари, Оператор ҳужжатлари, ушбу Шартнома билан белгиланган Тошкент шаҳрининг ахборот тизими, фойдаланувчи ушбу ахборот тизимидан фойдаланишга ҳақли эмас.</li>
                        <li>2.5. Сайтдаги материаллардан Интернетда ёки босма нусхада фойдаланганда манба кўрсатилиши шарт.</li>

                        <li>3. Тошкент шаҳрида фойдаланувчиларни рўйхатдан ўтказиш, хизматлардан, ахборот тизимлари ва ресурсларидан фойдаланиш</li>
                        <li>3.1. Фойдаланувчини Хизматда рўйхатдан ўтказиш Фойдаланувчи Хизматнинг веб-саҳифасида маълум бир маълумот тўпламини тақдим этгандан ва Хизматнинг талабларига мувофиқ Фойдаланувчи аккаунтни яратгандан сўнг амалга оширилади.</li>
                        <li>3.2. Хизматдан фойдаланишнинг ҳар қандай босқичида Фойдаланувчи аниқ ва тўлиқ маълумотларни тақдим этишга мажбурдир. Фойдаланувчи ўзи тақдим этган маълумотларни янгилаб туриш мажбуриятини олади. Агар Фойдаланувчи нотўғри маълумот тақдим этса ёки Оператор Фойдаланувчи томонидан тақдим этилган маълумот тўлиқ эмас ёки нотўғри эканлигига ишонч ҳосил қилса, Оператор ўз хоҳишига кўра фойдаланувчи аккаунтини блокировка қилишга ёки уни ўчиришга ва (ёки) фойдаланувчидан Хизматдан (ёки уларнинг индивидуал функцияларидан) воз кечишга ҳақлидир.</li>
                        <li>3.3. Хизматдан фойдаланиш, фойдаланувчининг ҳар қандай маълумотни, шу жумладан тўғри ишлаши ва / ёки тизим хизматларидан (шу жумладан cookie-файллардан) фойдаланиши ёки фойдаланувчи томонидан мустақил равишда тақдим этилган статистик маълумотларни тўплаши учун зарур бўлган маълумотларни қайта ишлашга розилигини англатади, шунингдек шахсий маълумотлар, шунингдек, давлат томонидан тақдим этилган маълумотлар тўғрисида маълумот олишга розилик билдиради шунингдек, унга давлат хизматлари кўрсатиш тўғрисида, Тошкент шаҳри давлат ҳокимияти ва унинг бўйсунувчи ташкилотлар, бошқа ташкилотлар фаолияти тўғрисида маълумот олишга розилик бериш. Кўрсатилган маълумотлар "Интернет" ахборот ва телекоммуникация тармоғи орқали маълумот юбориш орқали овозсиз алоқадан фойдаланган ҳолда (Хизматнинг ички воситалари орқали хабарларни юбориш ёки қисқа матнли СМС хабарларни мобил радиотелефон тармоғи орқали юбориш, ussd-сўров юбориш ва ҳк) Фойдаланувчи томонидан тақдим этилган телефон рақамига ва (ёки) электрон почта манзилига.</li>
                        <li>3.4. Фойдаланувчи ўзи фойдаланадиган паролнинг хавфсизлиги (тахмин қилишнинг қаршилиги) учун жавобгардир ва шунингдек, парол ва бошқа идентификация қилиш воситаларининг махфийлигини таъминлайди. Фойдаланувчи Фойдаланувчи томонидан хизмат ичида ёки ундан фойдаланишда содир бўлган барча ҳаракатлар (шунингдек уларнинг оқибатлари) учун, шу жумладан фойдаланувчи томонидан фойдаланувчи аккаунтига кириш учун маълумотни исталган шартлар билан учинчи шахсларга ихтиёрий равишда бериш ҳоллари учун (шу жумладан шартномалар ёки битмлар бўйича). Шу билан бирга, Фойдаланувчи аккаунтида амалга оширилган Хизмат ичидаги ёки ундан фойдаланувчи томонидан қилинган барча ҳаракатлар, фойдаланувчи томонидан амалга оширилган деб ҳисобланади, Фойдаланувчи ҳисобидан фойдаланган ҳолда Хизматга рухсатсиз кириш тўғрисида ва / ёки унинг паролининг махфийлиги бузилганлиги ва бошқа идентификатсия қилиш усуллари тўғрисида Операторга хабар беради.</li>
                        <li>3.5. Фойдаланувчи аккаунтидан фойдаланган ҳолда хизматга рухсатсиз кириш (фойдаланувчи томонидан тасдиқланмаган) ва / ёки унинг паролининг махфийлиги ёки бошқа идентификация қилиш воситаларининг бузилиши (бузилиш шубҳаси) тўғрисида ҳар қандай ҳолатлар тўғрисида Операторга дарҳол хабар қилиши шарт. Хавфсизлик мақсадида, фойдаланувчи ҳар бир иш сессиясининг охирида Хизматга қўйиладиган талабларга мувофиқ равишда ўз аккаунти бўйича ишларни хавфсиз равишда ўчириб қўйиши шарт. Оператор маълумотларни йўқолиши ёки шикастланиши, шунингдек Фойдаланувчи томонидан ушбу Шартноманинг қоидаларини бузиши натижасида юзага келиши мумкин бўлган ҳар қандай бошқа табиатнинг оқибатлари учун жавобгар бўлмайди.</li>
                        <li>3.6. Оператор ушбу Шартномаларда белгиланган ҳолларда, барча фойдаланувчиларнинг ёки баъзи фойдаланувчиларнинг аккаунтлари учун Хизматдан ва унинг қисмларидан фойдаланишга чекловлар ўрнатиш ҳуқуқига эга.</li>

                        <li>4. Томонларнинг ҳуқуқ ва мажбуриятлари</li>
                        <li>4.1. Фойдаланувчи қуйидагиларга мажбур:</li>
                        <li>4.1.1. Ўз кучи ва ўз ҳисобидан "Интернет" ахборот-телекоммуникация тармоғига киришни таъминлаши, шунингдек уларнинг ускуналарини рухсатсиз ишлатилишини созлаши ва ҳимоя қилиши, ва бундай фойдаланиш ҳолатлари аниқланганда тезкор чораларни кўриши.</li>
                        <li>4.1.2. Фойдаланувчи паролининг ва бошқа идентификация қилиш воситаларининг сақланишини таъминлаши керак.</li>
                        <li>4.1.3. Фойдаланувчи рўйхатдан ўтганидан кейин содир бўлган барча ҳисоб-китоблар орқали амалга оширилган барча сўровлар ва ҳаракатлар учун тўлиқ жавобгарликни ўз зиммасига олади.</li>
                        <li>4.1.4. Ушбу Шартнома шартларига риоя қилиш.</li>
                        <li>4.2. Фойдаланувчи қуйидаги ҳуқуқларга эга:</li>
                        <li>4.2.1. Хизматнинг функционал имкониятларидан тегишли хизматлар ва ахборот тизимларига қўйиладиган талабларга ва ушбу Шартномага мувофиқ фойдаланиш ҳуқуқига эга.</li>
                        <li>4.2.2. Белгиланган тартибда Операторга Хизматнинг техник ишлашига оид саволларни юбориш.</li>
                        <li>4.3. Хизматдан фойдаланганда, фойдаланувчи қуйидаги ҳуқуқларга эга эмас:</li>
                        <li>4.3.1. Ноқонуний, зарарли, туҳмат, ахлоқни бузувчи, зўравонлик ва шафқатсизликни намойиш қилувчи (ёки ташвиқот қиладиган), интеллектуал мулк ҳуқуқларини бузадиган, одамларга нисбатан нафратни ва / ёки камситишни тарғиб қилувчи таркибий қисмларни юклаш, юбориш, бошқа йўллар билан юбориш ёки тарқатиш, ирқий, этник, жинсий, диний, ижтимоий хусусиятлар, ҳар қандай шахс ёки ташкилотга нисбатан ҳақоратларни ўз ичига олган, порнография элементларини (ёки тарғиботни) ўз ичига олган, болалар эротиклиги, жинсий хизматларни реклама қилиш (ёки тарғиб қилиш), гиёҳвандлик воситаларини ёки уларнинг ўхшашларини, портловчи моддаларни ёки бошқа қуролларни тайёрлаш, ишлатиш ёки бошқа фойдаланиш тартибини тушунтиради.</li>
                        <li>4.3.2. Учинчи шахсларнинг, шу жумладан вояга етмаганларнинг ҳуқуқларини бузиш ва / ёки уларга ҳар қандай шаклда зарар етказиш.</li>
                        <li>4.3.3. Бошқа шахсни ёки ташкилотнинг ва / ёки жамоанинг вакилини, шу жумладан Оператор ходимларини, ҳуқуқларини ўзлаштирмаслик, шунингдек бошқаларнинг ноқонуний вакиллик қилишнинг бошқа шакллари ва усулларидан фойдаланиш, шунингдек фойдаланувчилар ёки Операторнинг хусусиятлари нисбатан чалғитиш ҳар қандай мавзу ёки объект.</li>
                        <li>4.3.4. Ўзбекистон Республикаси қонунларига, Тошкент шаҳрининг норматив-ҳуқуқий ҳужжатларига, Оператор актларига ёки ҳар қандай шартнома муносабатларига мувофиқ бундай ҳаракатларга ҳуқуқлари бўлмаган тақдирда, таркибни юклаш, юбориш, ёки бошқа усул билан тарқатиш.</li>
                        <li>4.3.5. Махсус рухсат этилмаган реклама ва спамларни юклаш, юбориш ёки бошқа усул билан тарқатиш.</li>
                        <li>4.3.6. Зарарли дастурларни ёки бошқа компьютер кодларини, файлларни ёки дастурларни ҳар қандай компьютер ёки телекоммуникация ускуналари ёки дастурларининг ишини бузиш, чеклаш, рухсатсиз ишлаш учун мўлжалланган материалларни юклаш, юбориш, бошқа йўл билан юбориш ва / ёки тарқатиш. тижорат дастурий маҳсулотларига ва уларни яратиш учун дастурларга серияли рақамларни, логинларни, паролларни ва "Интернет" ахборот-телекоммуникация тармоғида пулли манбалардан рухсатсиз киришни олиш учун бошқа воситаларни, шунингдек юқорида кўрсатилган маълумотларга ҳаволаларни жойлаштириш.</li>
                        <li>4.3.7. Бошқаларнинг шахсий маълумотларини рухсатсиз тўплаш ва сақлаш.</li>
                        <li>4.3.8. Хизматнинг нормал ишлашини бузиш;</li>
                        <li>4.3.9. Шартнома томонидан ўрнатилган чекловлар ва тақиқларни бузишга қаратилган ҳаракатларга ёрдам бериш.</li>
                        <li>4.3.10. Бошқа тарзда қонунни бузиш.</li>
                        <li>4.4. Оператор қуйидаги мажбуриятларни бажаради:</li>
                        <li>4.4.1. Операторнинг ваколатига тааллуқли Хизматнинг ишлашини таъминлаш, шунингдек Ўзбекистон Республикасининг қонунларида, Тошкент шаҳрининг норматив-ҳуқуқий ҳужжатларида, Оператор ҳужжатлари билан белгиланган бошқа ваколатларни амалга ошириш.</li>
                        <li>4.4.2. Фойдаланувчи билан ушбу Шартнома асосида Хизматга кириш ҳуқуқини бериш.</li>
                        <li>4.4.3. Белгиланган тартибда фойдаланувчи томонидан тақдим этилган маълумотларнинг сақланишини, хавфсизлигини ва ошкор қилинмаслигини таъминлаш.</li>
                        <li>4.4.4. Ушбу Шартномада назарда тутилган бошқа мажбуриятларни бажариш.</li>
                        <li>4.5. Оператор қуйидаги ҳуқуқларга эга:</li>
                        <li>4.5.1. Ўзбекистон Республикасининг қонунларида, Тошкент шаҳрининг норматив-ҳуқуқий ҳужжатларида, ушбу Шартномада кўзда тутилган ҳолларда, Фойдаланувчини рўйхатдан ўтиш ва хизматнинг имкониятларидан фойдаланишни рад этиш</li>
                        <li>4.5.2. Фойдаланувчи томонидан қуйидаги ҳолларда огоҳлантиришсиз Хизматдан фойдаланишни тўхтатиб қўйиш:
                            <ul>
                                <li>•	Фойдаланувчи томонидан ушбу Шартнома шартлари бузилиши ёки Фойдаланувчи томонидан Оператор ушбу Шартнома шартларини бузган деб ҳисоблаган хатти-ҳаракатларни амалга оширса;</li>
                                <li>•	кутилмаган техник ёки хавфсизлик муаммолари туфайли;</li>
                                <li>•	фойдаланувчининг Тошкент шаҳри хизматлари, ахборот тизимлари ва ресурсларига, шу жумладан ҳар қандай қурилмалар, дастурий таъминотлардан фойдаланишига тўсқинлик қилиши ва ҳар қандай ҳуқуқбузарликлар туфайли.</li>
                            </ul>
                        </li>
                        <li>4.5.3. Фойдаланувчига Хизматнинг ишлаши, шунингдек Оператор ва Тошкент шаҳридаги бошқа ижро органлари, ташкилотлар фаолияти тўғрисида ташкилий ва техник маълумотларни ўз ичига олган хабарларни юбориш.</li>
                        <li>4.5.4. Тошкент шаҳри хизматлари ва ахборот тизимлари ишини таъминлашга, Тошкент шаҳрининг ахборот ресурсларини белгиланган тартибда сақлашга учинчи шахсларни жалб қилиш.</li>
                        <li>4.5.5. Уларнинг фаолияти вақтинча тўхтатиб қўйилган ҳолда Тошкент шаҳар хизматлари ва ахборот тизимларида профилактика ишларини олиб бориш.</li>
                        <li>4.6. Оператор қуйидаги учун жавобгар эмас:</li>
                        <li>4.6.1. Учинчи шахслар томонидан этказиб бериладиган, этказиб бериладиган, ишлайдиган ва / ёки хизмат кўрсатадиган асбоб-ускуналар, алоқа тизимлари ёки тармоқларининг носозликлари билан боғлиқ бўлган, хизматга киришда хизматдаги авариялар, узилишлар ёки узилишлар.</li>
                        <li>4.6.2. Фойдаланувчи томонидан етказилган зарар:
                            <ul>
                                <li>•	Фойдаланувчи томонидан хизматга кириш учун фойдаланадиган асбоб-ускуналар ва дастурларда "вируслар" ва бошқа зарарли дастурларнинг мавжудлиги;</li>
                                <li>•	Фойдаланувчи ушбу Шартномани бузса;</li>
                                <li>•	учинчи шахсларнинг ноқонуний хатти-ҳаракатлари, шу жумладан Фойдаланувчи аккаунтидан фойдаланиш билан боғлиқ, шунингдек, хизматдан фойдаланиш пайтида у тақдим этган фойдаланувчи тўғрисидаги маълумотлардан, агар бундай маълумотлар Операторнинг айбисиз учинчи шахсларга етказилган бўлса.</li>
                            </ul>
                        </li>
                        <li>4.7. Фойдаланувчи ва Оператор ушбу Шартномани бажармаганлиги ёки лозим даражада бажармаганлиги учун жавобгар эмас, агар енгиб бўлмас куч таъсирида юзага келганлиги сабабли уни бажариш имкони бўлмаса.</li>
                        <li>5. Бошқа шартлар</li>
                        <li>5.1. Ушбу Битим Ўзбекистон Республикасининг қонунларига мувофиқ тартибга солинади ва шарҳланади. Ушбу Битим билан тартибга солинмаган масалалар Ўзбекистон Республикаси қонунларига мувофиқ ҳал қилиниши керак. Ушбу Шартнома билан тартибга солинадиган муносабатлардан келиб чиқадиган барча мумкин бўлган тортишувлар Ўзбекистон Республикасининг амалдаги қонунчилигида белгиланган тартибда ҳал қилинади.</li>
                        <li>5.2. Ушбу Шартноманинг шартлари, агар Ўзбекистон Республикаси қонунларида ва Тошкент шаҳрининг норматив-ҳуқуқий ҳужжатларида бошқача қоида назарда тутилган бўлмаса, томонлардан бири ушбу Битимдан чиқиш нияти тўғрисида билдирган пайтгача амал қилади.</li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
@endsection
