<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLocationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('locations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('uz_title');
            $table->string('ru_title');
            $table->string('cyrillic_uz_title');
            $table->string('uz_region');
            $table->string('cyrillic_uz_region');
            $table->string('ru_region');
            $table->string('coords_lat');
            $table->string('coords_lng');
            $table->string("type");
            $table->string('city')->nullable();
            $table->timestamps();
        });
        $position = 1;
        DB::connection('mysql')->table('locations')->insert([

            [
                'uz_title'          => 'Epidemiologiya, mikrobiologiya va yuqumli kasalliklar ilmiy tekshirish instituti klinikasi',
                'ru_title'          => 'Клиника НИИ эпидемиологии, микробиологии, инфекционных болезней',
                'cyrillic_uz_title' => 'Эпидемиология, микробиология ва юқумли касалликлар илмий текшириш институти клиникаси',
                'uz_region'             => "Uchtepa tumani",
                'cyrillic_uz_region'    => "Учтепа тумани",
                'ru_region'             => "Учтепинский р-н.",
                'coords_lat' => '41.310318',
                'coords_lng' => "69.187578",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Virusologiya ilmiy tekshirish instituti',
                'ru_title'          => 'Институт вирусологии',
                'cyrillic_uz_title' => 'Вирусология илмий текшириш институти',
                'uz_region'             => "Yunusobod tum.",
                'cyrillic_uz_region'    => "Юнусобод тум.",
                'ru_region'             => "Юнусабадский р-н.",
                'coords_lat' => '41.360605',
                'coords_lng' => "69.300987",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika 1-son klinik kasalxonasi',
                'ru_title'          => 'Респуб. клиническая больница № 1',
                'cyrillic_uz_title' => 'Республика 1-сон клиник касалхонаси',
                'uz_region'             => "Mirobod tum.",
                'cyrillic_uz_region'    => "Миробод тум.",
                'ru_region'             => "Мирабадский р-н.",
                'coords_lat' => '41.301600',
                'coords_lng' => "69.284659",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Travmatologiya va ortopediya ilmiy amaliy tibbiyot markazi',
                'ru_title'          => 'НИИ травматологии и ортопедии',
                'cyrillic_uz_title' => 'Травматология ва ортопедия илмий амалий тиббиёт маркази',
                'uz_region'             => "Yashnobod tum.",
                'cyrillic_uz_region'    => "Яшнобод тум.",
                'ru_region'             => "Яшнабадский р-н.",
                'coords_lat' => '41.306502',
                'coords_lng' => "69.293572",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika nogironlar reabilitatsiyasi markazi',
                'ru_title'          => 'Респуб. центр реабилитации и протезирования инвалидов',
                'cyrillic_uz_title' => 'Республика ногиронлар реабилитацияси маркази',
                'uz_region'             => "Mirzo Ulugʼbek tum.",
                'cyrillic_uz_region'    => "Мирзо Улуғбек тум.",
                'ru_region'             => "Мирзо Улугбекский р-н.",
                'coords_lat' => '41.334731',
                'coords_lng' => "69.306560",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Nuroniylar sanatoriyasi',
                'ru_title'          => 'Санаторий Нуронийлар',
                'cyrillic_uz_title' => 'Нуронийлар санаторияси',
                'uz_region'             => "Yunusobod tum.",
                'cyrillic_uz_region'    => "Юнусобод тум.",
                'ru_region'             => "Юнусабадский р-н.",
                'coords_lat' => '41.380572',
                'coords_lng' => "69.316548",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika bolalar ortopediya markazi',
                'ru_title'          => 'Респ. центр детской ортопедии',
                'cyrillic_uz_title' => 'Республика болалар ортопедия маркази',
                'uz_region'             => "Qibray tum.",
                'cyrillic_uz_region'    => "Қибрай тум.",
                'ru_region'             => "Кибрайский р-н.",
                'coords_lat' => '41.362306',
                'coords_lng' => "69.342024",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar 3-son tugʼruq kompleksi',
                'ru_title'          => 'Родильный комплекс №3 г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 3-сон туғруқ комплекси',
                'uz_region'             => "Olmazor tum.",
                'cyrillic_uz_region'    => "Олмазор тум.",
                'ru_region'             => "Алмазарский р-н.",
                'coords_lat' => '41.344223',
                'coords_lng' => "69.261070",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Bolalar suyak sili sanatoriyasi',
                'ru_title'          => 'Детский санаторий для больных костным туберкулезом',
                'cyrillic_uz_title' => 'Болалар суяк сили санаторияси',
                'uz_region'             => "Mirzo Ulugʼbek tum.",
                'cyrillic_uz_region'    => "Мирзо Улуғбек тум.",
                'ru_region'             => "Мирзо Улугбекский р-н.",
                'coords_lat' => '41.353865',
                'coords_lng' => "69.377467",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Инфекционная больница №2 г. Ташкента',
                'ru_title'          => 'Toshkent shahar 2-son yuqumli kasalliklar shifoxonasi',
                'cyrillic_uz_title' => 'Тошкент шаҳар 2-сон юқумли касалликлар шифохонаси',
                'uz_region'             => "Yashnobod tum.",
                'cyrillic_uz_region'    => "Яшнобод тум.",
                'ru_region'             => "Яшнабадский р-н.",
                'coords_lat' => '41.269767',
                'coords_lng' => "69.325119",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent viloyat somatika shifoxonasi',
                'ru_title'          => 'Таш. обл. центр. соматическая больница',
                'cyrillic_uz_title' => 'Тошкент вилоят соматика шифохонаси',
                'uz_region'             => "Chilonzor tum.",
                'cyrillic_uz_region'    => "Чилонзор тум.",
                'ru_region'             => "Чиланзарский р-н.",
                'coords_lat' => '41.288714',
                'coords_lng' => "69.218319",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika teri tanosil kasalliklar shifoxonasi',
                'ru_title'          => 'Респ. кожвен. больница',
                'cyrillic_uz_title' => 'Республика тери таносил касалликлар шифохонаси',
                'uz_region'             => "Mirobod tum.",
                'cyrillic_uz_region'    => "Миробод тум.",
                'ru_region'             => "Мирабадский р-н.",
                'coords_lat' => '41.295848',
                'coords_lng' => "69.289744",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar 3-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №3  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 3-сон клиник шифохонаси',
                'uz_region'             => "Mirobod tum.",
                'cyrillic_uz_region'    => "Миробод тум.",
                'ru_region'             => "Мирабадский р-н.",
                'coords_lat' => '41.272465',
                'coords_lng' => "69.306793",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar tez tibbiy yordam shifoxonasi',
                'ru_title'          => 'Центр экстренной мед. помощи  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар тез тиббий ёрдам шифохонаси',
                'uz_region'             => "Chilonzor tum.",
                'cyrillic_uz_region'    => "Чилонзор тум.",
                'ru_region'             => "Чиланзарский р-н.",
                'coords_lat' => '41.268431',
                'coords_lng' => "69.217166",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar 6-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №6  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 6-сон клиник шифохонаси',
                'uz_region'             => "Bektemir tum.",
                'cyrillic_uz_region'    => "Бектемир тум.",
                'ru_region'             => "Бектемирский р-н.",
                'coords_lat' => '41.232185',
                'coords_lng' => "69.330792",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'              => 'Toshkent tibbiy akademiyasining koʼp tarmoqli klinikasi (yangi Toshmi)',
                'cyrillic_uz_title'     => 'Тошкент тиббий академиясининг кўп тармоқли клиникаси (янги Тошми)',
                'ru_title'              => 'Медицинская академия г. Ташкента (новое Ташми) многопрофил. клиника',
                'uz_region'             => "Olmazor tumani",
                'cyrillic_uz_region'    => "Олмазор тумани",
                'ru_region'             => "Алмазарский р-н.",
                'coords_lat' => '41.350952',
                'coords_lng' => "69.171804",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respub. ixtisos. terapiya va tibbiy reabilitatsiya ilmiy amaliy tibbiyot markazi',
                'ru_title'          => 'Респуб. науч. исслед. медцентр спец. терапии и медреабилитации',
                'cyrillic_uz_title' => 'Респуб. ихтисос. терапия ва тиббий реабилитация илмий амалий тиббиёт маркази',
                'uz_region'             => "Yunusobod tum.",
                'cyrillic_uz_region'    => "Юнусобод тум.",
                'ru_region'             => "Юнусабадский р-н.",
                'coords_lat' => '41.337309',
                'coords_lng' => "69.279609",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shaxar 1-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №1 г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шахар 1-сон клиник шифохонаси',
                'uz_region'             => "Shayxontahur tum.",
                'cyrillic_uz_region'    => "Шайхонтаҳур тум.",
                'ru_region'             => "Шайхонтахурский р-н.",
                'coords_lat' => '41.321520',
                'coords_lng' => "69.219756",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika 2-son klinik kasalxonasi',
                'ru_title'          => 'Респуб. клиническая больница № 2',
                'cyrillic_uz_title' => 'Республика 2-сон клиник касалхонаси',
                'uz_region'             => "Mirzo Ulugʼbek tum.",
                'cyrillic_uz_region'    => "Мирзо Улуғбек тум.",
                'ru_region'             => "Мирзо Улугбекский р-н.",
                'coords_lat' => '41.403546',
                'coords_lng' => "69.449170",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika koʼz kasalliklari shifoxonasi',
                'ru_title'          => 'Респуб. офтальмологическая больница',
                'cyrillic_uz_title' => 'Республика кўз касалликлари шифохонаси',
                'uz_region'             => "Olmazor tum.",
                'cyrillic_uz_region'    => "Олмазор тум.",
                'ru_region'             => "Алмазарский р-н.",
                'coords_lat' => '41.354512',
                'coords_lng' => "69.217555",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Zangiota 1-son yuqumli kasalliklar shifoxonasi',
                'ru_title'          => 'Зангиатинская инфекционная больница №1',
                'cyrillic_uz_title' => 'Зангиота 1-сон юқумли касалликлар шифохонаси',
                'uz_region'             => "Zangiota tum.",
                'cyrillic_uz_region'    => "Зангиота тум.",
                'ru_region'             => "Зангиатинский р-н.",
                'coords_lat' => '41.176099',
                'coords_lng' => "69.194044",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Zangiota 2-son yuqumli kasalliklar shifoxonasi',
                'ru_title'          => 'Зангиатинская инфекционная больница №2',
                'cyrillic_uz_title' => 'Зангиота 2-сон юқумли касалликлар шифохонаси',
                'uz_region'             => "Zangiota tum.",
                'cyrillic_uz_region'    => "Зангиота тум.",
                'ru_region'             => "Зангиатинский р-н.",
                'coords_lat' => '41.170042',
                'coords_lng' => "69.193272",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Yakkasaroy koʼp tarmoqli markaziy poliklinikasi',
                'ru_title'          => 'Яккасарайская многоотраслевая центр. поликлиника',
                'cyrillic_uz_title' => 'Яккасарой кўп тармоқли марказий поликлиникаси',
                'uz_region'             => "Yakkasaroy tum.",
                'cyrillic_uz_region'    => "Яккасарой тум.",
                'ru_region'             => "Яккасарайский р-н.",
                'coords_lat' => '41.276720',
                'coords_lng' => "69.242501",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => '«Urtasaroy» Covid-19 karantin zonasi',
                'ru_title'          => 'Карантинная зона Covid-19 «Уртасарой»',
                'cyrillic_uz_title' => '«Уртасарой» Covid-19 карантин зонаси',
                'uz_region'             => "Yuqorichirchiq tum.",
                'cyrillic_uz_region'    => "Юқоричирчиқ тум.",
                'ru_region'             => "Юкоричирчикский р-н.",
                'coords_lat' => '41.120849',
                'coords_lng' => "69.52399",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'UzEkspoMarkaz taqsimlash markazi',
                'ru_title'          => 'УзЭкспоЦентр распред. центр',
                'cyrillic_uz_title' => 'УзЭкспоМарказ тақсимлаш маркази',
                'uz_region'             => "Yunusobod tum.",
                'cyrillic_uz_region'    => "Юнусобод тум.",
                'ru_region'             => "Юнусабадский р-н.",
                'coords_lat' => '41.339067',
                'coords_lng' => "69.28003",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar tez tibbiy yordam shifoxonasi',
                'ru_title'          => 'Клиническая больница скорой помощи г. Ташкента (Жуковская)',
                'cyrillic_uz_title' => 'Тошкент шаҳар тез тиббий ёрдам шифохонаси (Жуковский)',
                'uz_region'             => "Uchtepa tum.",
                'cyrillic_uz_region'    => "Учтепа тум.",
                'ru_region'             => "Учтепинский р-н.",
                'coords_lat' => '41.298756',
                'coords_lng' => "69.190461",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar 2-son bollalar jarroxlik shifoxonasi',
                'ru_title'          => 'Городская детская хирургическая больница №2',
                'cyrillic_uz_title' => 'Тошкент шаҳар 2-сон боллалар жаррохлик шифохонаси',
                'uz_region'             => "Mirzo Ulugʼbek tum.",
                'cyrillic_uz_region'    => "Мирзо Улуғбек тум.",
                'ru_region'             => "Мирзо Улугбекский р-н.",
                'coords_lat' => '41.330308',
                'coords_lng' => "69.335994",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Toshkent shahar 4-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №4 г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 4-сон клиник шифохонаси ',
                'uz_region'             => "Yashnobod tum.",
                'cyrillic_uz_region'    => "Яшнобод тум.",
                'ru_region'             => "Яшнабадский р-н.",
                'coords_lat' => '41.288313',
                'coords_lng' => "69.347083",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Pediatriya tibbiyot markazi',
                'ru_title'          => 'Медицинский центр педиатрии',
                'cyrillic_uz_title' => 'Педиатрия тиббиёт маркази',
                'uz_region'             => "Olmazor tum.",
                'cyrillic_uz_region'    => "Олмазор тум.",
                'ru_region'             => "Алмазарский р-н.",
                'coords_lat' => '41.359109',
                'coords_lng' => "69.198027",
                'type' => 'gos',
                'city' => null,
            ],
            [
                'uz_title'          => 'Diyor medical centre',
                'ru_title'          => 'Diyor medical centre',
                'cyrillic_uz_title' => 'Diyor medical centre',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.300181',
                'coords_lng' => "69.271447",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Medicus centre',
                'ru_title'          => 'Medicus centre',
                'cyrillic_uz_title' => 'Medicus centre',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.253080',
                'coords_lng' => "69.312830",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Monada-amon shifo',
                'ru_title'          => 'Monada-amon shifo',
                'cyrillic_uz_title' => 'Monada-amon shifo',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.283409',
                'coords_lng' => "69.301476",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Asia Med Center',
                'ru_title'          => 'Asia Med Center',
                'cyrillic_uz_title' => 'Asia Med Center',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.286870',
                'coords_lng' => "69.187709",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Darmon Diagnostika',
                'ru_title'          => 'Darmon Diagnostika',
                'cyrillic_uz_title' => 'Darmon Diagnostika',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.285766',
                'coords_lng' => "69.184757",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Neuro reability',
                'ru_title'          => 'Neuro reability',
                'cyrillic_uz_title' => 'Neuro reability',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.276214',
                'coords_lng' => "69.189844",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Urologic complex',
                'ru_title'          => 'Urologic complex',
                'cyrillic_uz_title' => 'Urologic complex',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.280437',
                'coords_lng' => "69.189550",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Respublika sport tibbiyoti',
                'ru_title'          => 'Respublika sport tibbiyoti',
                'cyrillic_uz_title' => 'Respublika sport tibbiyoti',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.316576',
                'coords_lng' => "69.254952",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Shahlo shifo',
                'ru_title'          => 'Shahlo shifo',
                'cyrillic_uz_title' => 'Shahlo shifo',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.283409',
                'coords_lng' => "69.301476",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Zdorovye vsem',
                'ru_title'          => 'Zdorovye vsem',
                'cyrillic_uz_title' => 'Zdorovye vsem',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.299845',
                'coords_lng' => "69.271427",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => "G'ulomjon neyro servis",
                'ru_title'          => "G'ulomjon neyro servis",
                'cyrillic_uz_title' => "G'ulomjon neyro servis",
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.295662',
                'coords_lng' => "69.334891",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'MDS-SERVIS',
                'ru_title'          => 'MDS-SERVIS',
                'cyrillic_uz_title' => 'MDS-SERVIS',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.309860',
                'coords_lng' => "69.317914",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Medion clinic',
                'ru_title'          => 'Medion clinic',
                'cyrillic_uz_title' => 'Medion clinic',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.329459',
                'coords_lng' => "69.258315",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Dil-savdo',
                'ru_title'          => 'Dil-savdo',
                'cyrillic_uz_title' => 'Dil-savdo',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.322282',
                'coords_lng' => "69.217402",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Invivo clinic',
                'ru_title'          => 'Invivo clinic',
                'cyrillic_uz_title' => 'Invivo clinic',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.348455',
                'coords_lng' => "69.170898",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Saif-optima',
                'ru_title'          => 'Saif-optima',
                'cyrillic_uz_title' => 'Saif-optima',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.293870',
                'coords_lng' => "69.333204",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Vita Stimul Med',
                'ru_title'          => 'Vita Stimul Med',
                'cyrillic_uz_title' => 'Vita Stimul Med',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.269700',
                'coords_lng' => "69.191260",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Doktor-servis',
                'ru_title'          => 'Doktor-servis',
                'cyrillic_uz_title' => 'Doktor-servis',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.298267',
                'coords_lng' => "69.214222",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Era med',
                'ru_title'          => 'Era med',
                'cyrillic_uz_title' => 'Era med',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.304987',
                'coords_lng' => "69.310980",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Omega Med',
                'ru_title'          => 'Omega Med',
                'cyrillic_uz_title' => 'Omega Med',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.339372',
                'coords_lng' => "69.337813",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'All med service',
                'ru_title'          => 'All med service',
                'cyrillic_uz_title' => 'All med service',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.328251',
                'coords_lng' => "69.339025",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Shox Med Center',
                'ru_title'          => 'Shox Med Center',
                'cyrillic_uz_title' => 'Shox Med Center',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.292230',
                'coords_lng' => "69.279810",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Shams Medical Center',
                'ru_title'          => 'Shams Medical Center',
                'cyrillic_uz_title' => 'Shams Medical Center',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.252665',
                'coords_lng' => "69.311717",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Olam-Plast Tijorat',
                'ru_title'          => 'Olam-Plast Tijorat',
                'cyrillic_uz_title' => 'Olam-Plast Tijorat',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.278181',
                'coords_lng' => "69.164999",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Tibbiyot Olami ',
                'ru_title'          => 'Tibbiyot Olami ',
                'cyrillic_uz_title' => 'Tibbiyot Olami ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.294800',
                'coords_lng' => "69.193379",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Olam ',
                'ru_title'          => 'Olam ',
                'cyrillic_uz_title' => 'Olam ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.278273',
                'coords_lng' => "69.165202",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Jacksoft  ',
                'ru_title'          => 'Jacksoft  ',
                'cyrillic_uz_title' => 'Jacksoft  ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.294555',
                'coords_lng' => "69.173836",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Cardio Star Plus',
                'ru_title'          => 'Cardio Star Plus',
                'cyrillic_uz_title' => 'Cardio Star Plus',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.265402',
                'coords_lng' => "69.217681",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Oftob Medline  ',
                'ru_title'          => 'Oftob Medline  ',
                'cyrillic_uz_title' => 'Oftob Medline  ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.337249',
                'coords_lng' => "69.255196",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'New Life Medical ',
                'ru_title'          => 'New Life Medical ',
                'cyrillic_uz_title' => 'New Life Medical ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.346397',
                'coords_lng' => "69.204695",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Камолахон Сервис Мед  ',
                'ru_title'          => 'Камолахон Сервис Мед  ',
                'cyrillic_uz_title' => 'Камолахон Сервис Мед  ',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.352129',
                'coords_lng' => "69.213849",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Komplex Med',
                'ru_title'          => 'Komplex Med',
                'cyrillic_uz_title' => 'Komplex Med',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.314295',
                'coords_lng' => "69.23843",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Doktor M',
                'ru_title'          => 'Doktor M',
                'cyrillic_uz_title' => 'Doktor M',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.354237',
                'coords_lng' => "69.288781",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'AKFA Medline',
                'ru_title'          => 'AKFA Medline',
                'cyrillic_uz_title' => 'AKFA Medline',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.342915',
                'coords_lng' => "69.208814",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Happy life',
                'ru_title'          => 'Happy life',
                'cyrillic_uz_title' => 'Happy life',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.377277',
                'coords_lng' => "69.313667",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Asad',
                'ru_title'          => 'Asad',
                'cyrillic_uz_title' => 'Asad',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.374047',
                'coords_lng' => "69.261165",
                'type' => 'personal',
                'city' => null,
            ],
            [
                'uz_title'          => 'Yunusobod Medical Center',
                'ru_title'          => 'Yunusobod Medical Center',
                'cyrillic_uz_title' => 'Yunusobod Medical Center',
                'uz_region'             => "",
                'cyrillic_uz_region'    => "",
                'ru_region'             => "",
                'coords_lat' => '41.383219',
                'coords_lng' => "69.29829",
                'type' => 'personal',
                'city' => null,
            ],
        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('locations');
    }
}
