<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLocationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('locations', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('uz_title');
            $table->string('ru_title');
            $table->string('cyrillic_uz_title');
            $table->string('coords_lat');
            $table->string('coords_lng');
            $table->string('number')->nullable();
            $table->string('location_email')->nullable();
            $table->string('addressline1')->nullable();
            $table->string('addressline2')->nullable();
            $table->string('city')->nullable();
            $table->string('country')->nullable();
            $table->timestamps();
        });
        $position = 1;
        DB::connection('mysql')->table('locations')->insert([

            [
                'uz_title'          => 'Epidemiologiya, mikrobiologiya va yuqumli kasalliklar ilmiy tekshirish instituti klinikasi',
                'ru_title'          => 'Клиника НИИ эпидемиологии, микробиологии, инфекционных болезней',
                'cyrillic_uz_title' => 'Эпидемиология, микробиология ва юқумли касалликлар илмий текшириш институти клиникаси',
                'coords_lat' => '41.310318',
                'coords_lng' => "69.187578",
                'number' => "",
                'location_email' => "",
                'addressline1' => " Заковат, 2",
                'addressline2' => "Учтепа тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Virusologiya ilmiy tekshirish instituti',
                'ru_title'          => 'Институт вирусологии',
                'cyrillic_uz_title' => 'Вирусология илмий текшириш институти',
                'coords_lat' => '41.360605',
                'coords_lng' => "69.300987",
                'number' => "",
                'location_email' => "",
                'addressline1' => "\"Янгишаҳар\" кўчаси, 7-а уй",
                'addressline2' => "Юнусобод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika 1-son klinik kasalxonasi',
                'ru_title'          => 'Респуб. клиническая больница № 1',
                'cyrillic_uz_title' => 'Республика 1-сон клиник касалхонаси',
                'coords_lat' => '41.301600',
                'coords_lng' => "69.284659",
                'number' => "",
                'location_email' => "",
                'addressline1' => "\"Содиқ Азимов\" кўчаси, 74 уй",
                'addressline2' => "Миробод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Travmatologiya va ortopediya ilmiy amaliy tibbiyot markazi',
                'ru_title'          => 'НИИ травматологии и ортопедии',
                'cyrillic_uz_title' => 'Травматология ва ортопедия илмий амалий тиббиёт маркази',
                'coords_lat' => '41.306502',
                'coords_lng' => "69.293572",
                'number' => "",
                'location_email' => "",
                'addressline1' => "78 Taraqqiyot ko'chasi, Тошкент 100047",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika nogironlar reabilitatsiyasi markazi',
                'ru_title'          => 'Респуб. центр реабилитации и протезирования инвалидов',
                'cyrillic_uz_title' => 'Республика ногиронлар реабилитацияси маркази',
                'coords_lat' => '41.334731',
                'coords_lng' => "69.306560",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Nuroniylar sanatoriyasi',
                'ru_title'          => 'Санаторий Нуронийлар',
                'cyrillic_uz_title' => 'Нуронийлар санаторияси',
                'coords_lat' => '41.380572',
                'coords_lng' => "69.316548",
                'number' => "",
                'location_email' => "",
                'addressline1' => "19-квартал",
                'addressline2' => "Юнусобод тумани ",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika bolalar ortopediya markazi',
                'ru_title'          => 'Респ. центр детской ортопедии',
                'cyrillic_uz_title' => 'Республика болалар ортопедия маркази',
                'coords_lat' => '41.362306',
                'coords_lng' => "69.342024",
                'number' => "",
                'location_email' => "",
                'addressline1' => " \"Олийгох\" кўчаси 8 уй (сельхоз институт худуди ичида №8 бино)",
                'addressline2' => "\"Солор\" шаҳарчаси",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent shahar 3-son tugʼruq kompleksi',
                'ru_title'          => 'Родильный комплекс №3 г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 3-сон туғруқ комплекси',
                'coords_lat' => '41.344223',
                'coords_lng' => "69.261070",
                'number' => "",
                'location_email' => "",
                'addressline1' => "ул. ТАХТАПУЛ ДАРВОЗА (бывш. С.РАХИМОВА), 351",
                'addressline2' => "Алмазарский",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Bolalar suyak sili sanatoriyasi',
                'ru_title'          => 'Детский санаторий для больных костным туберкулезом',
                'cyrillic_uz_title' => 'Болалар суяк сили санаторияси',
                'coords_lat' => '41.353865',
                'coords_lng' => "69.377467",
                'number' => "",
                'location_email' => "",
                'addressline1' => "\"Буюк ипак йўли\"кўчаси, 425 уй",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Инфекционная больница №2 г. Ташкента',
                'ru_title'          => 'Toshkent shahar 2-son yuqumli kasalliklar shifoxonasi',
                'cyrillic_uz_title' => 'Тошкент шаҳар 2-сон юқумли касалликлар шифохонаси',
                'coords_lat' => '41.269767',
                'coords_lng' => "69.325119",
                'number' => "",
                'location_email' => "",
                'addressline1' => "  \"Жарқўрғон\" кўчаси, 39 уй",
                'addressline2' => "Яшнобод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent viloyat somatika shifoxonasi',
                'ru_title'          => 'Таш. обл. центр. соматическая больница',
                'cyrillic_uz_title' => 'Тошкент вилоят соматика шифохонаси',
                'coords_lat' => '41.288714',
                'coords_lng' => "69.218319",
                'number' => "",
                'location_email' => "",
                'addressline1' => "12 Бунёдкор кўчаси,",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika teri tanosil kasalliklar shifoxonasi',
                'ru_title'          => 'Респ. кожвен. больница',
                'cyrillic_uz_title' => 'Республика тери таносил касалликлар шифохонаси',
                'coords_lat' => '41.295848',
                'coords_lng' => "69.289744",
                'number' => "",
                'location_email' => "",
                'addressline1' => " Нукус, 14",
                'addressline2' => "Миробод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent shahar 3-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №3  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 3-сон клиник шифохонаси',
                'coords_lat' => '41.272213',
                'coords_lng' => "69.307011",
                'number' => "",
                'location_email' => "",
                'addressline1' => "\"А. Фитрат\" кўчаси, 20 уй",
                'addressline2' => "Миробод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent shahar tez tibbiy yordam shifoxonasi',
                'ru_title'          => 'Центр экстренной мед. помощи  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар тез тиббий ёрдам шифохонаси',
                'coords_lat' => '41.268431',
                'coords_lng' => "69.217166",
                'number' => "",
                'location_email' => "",
                'addressline1' => "Фарҳод кўчаси, 2",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent shahar 6-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №6  г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шаҳар 6-сон клиник шифохонаси',
                'coords_lat' => '41,232185',
                'coords_lng' => "69,330792",
                'number' => "",
                'location_email' => "",
                'addressline1' => "\"Боғишамол\" кўчаси, 112 уй",
                'addressline2' => "Юнусобод ",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent tibbiy akademiyasining koʼp tarmoqli klinikasi (yangi Toshmi)',
                'ru_title'          => 'Медицинская академия г. Ташкента (новое Ташми) многопрофил. клиника',
                'cyrillic_uz_title' => 'Тошкент тиббий академиясининг кўп тармоқли клиникаси (янги Тошми)',
                'coords_lat' => '41.350952',
                'coords_lng' => "69.171804",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "Олмазор тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respub. ixtisos. terapiya va tibbiy reabilitatsiya ilmiy amaliy tibbiyot markazi',
                'ru_title'          => 'Респуб. науч. исслед. медцентр спец. терапии и медреабилитации',
                'cyrillic_uz_title' => 'Респуб. ихтисос. терапия ва тиббий реабилитация илмий амалий тиббиёт маркази',
                'coords_lat' => '41.337309',
                'coords_lng' => "69.279609",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "Юнусабод тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Toshkent shaxar 1-son klinik shifoxonasi',
                'ru_title'          => 'Клиническая больница №1 г. Ташкента',
                'cyrillic_uz_title' => 'Тошкент шахар 1-сон клиник шифохонаси',
                'coords_lat' => '41.321520',
                'coords_lng' => "69.219756",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika 2-son klinik kasalxonasi',
                'ru_title'          => 'Респуб. клиническая больница № 2',
                'cyrillic_uz_title' => 'Республика 2-сон клиник касалхонаси',
                'coords_lat' => '41.403546',
                'coords_lng' => "69.449170",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "Мирзо Улуғбек тумани",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Respublika koʼz kasalliklari shifoxonasi',
                'ru_title'          => 'Респуб. офтальмологическая больница',
                'cyrillic_uz_title' => 'Республика кўз касалликлари шифохонаси',
                'coords_lat' => '41.354512',
                'coords_lng' => "69.217555",
                'number' => "",
                'location_email' => "",
                'addressline1' => "Зиёд кўчаси 12 уй",
                'addressline2' => "Қорақамиш,",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Zangiota 1-son yuqumli kasalliklar shifoxonasi',
                'ru_title'          => 'Зангиатинская инфекционная больница №1',
                'cyrillic_uz_title' => 'Зангиота 1-сон юқумли касалликлар шифохонаси',
                'coords_lat' => '41.176099',
                'coords_lng' => "69.194044",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Zangiota 2-son yuqumli kasalliklar shifoxonasi',
                'ru_title'          => 'Зангиатинская инфекционная больница №2',
                'cyrillic_uz_title' => 'Зангиота 2-сон юқумли касалликлар шифохонаси',
                'coords_lat' => '41.170042',
                'coords_lng' => "69.193272",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'Yakkasaroy koʼp tarmoqli markaziy poliklinikasi',
                'ru_title'          => 'Яккасарайская многоотраслевая центр. поликлиника',
                'cyrillic_uz_title' => 'Яккасарой кўп тармоқли марказий поликлиникаси',
                'coords_lat' => '41.276720',
                'coords_lng' => "69.242501",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => '«Urtasaroy» Covid-19 karantin zonasi',
                'ru_title'          => 'Карантинная зона Covid-19 «Уртасарой»',
                'cyrillic_uz_title' => '«Уртасарой» Covid-19 карантин зонаси',
                'coords_lat' => '41.120849',
                'coords_lng' => "69.52399",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
            [
                'uz_title'          => 'UzEkspoMarkaz taqsimlash markazi',
                'ru_title'          => 'УзЭкспоЦентр распред. центр',
                'cyrillic_uz_title' => 'УзЭкспоМарказ тақсимлаш маркази',
                'coords_lat' => '41.339067',
                'coords_lng' => "69.28003",
                'number' => "",
                'location_email' => "",
                'addressline1' => "",
                'addressline2' => "",
                'city' => "",
                'country' => "",
            ],
        ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('locations');
    }
}
